import { Video, Comment } from "@/types";

export const INITIAL_VIDEOS: Video[] = [
  {
    id: "citra-1",
    title: "Echoes of the Ghats: A Cinematic Journey Through Varanasi at Twilight",
    description: "Experience the eternal rhythm of Varanasi. From the flickering lamps of the Ganga Aarti to timeless boat journeys across mystical waters, immerse yourself in a continuous stream of visual and sonic wonders captured in ultra-high definition.",
    driveFileId: "1p0GqLq1j9g6v5n0d",
    driveUrl: "https://drive.google.com/file/d/1B69oDffW-q_2Xl1Z5z6K-K7v48b5zX9y/view",
    embedUrl: "https://drive.google.com/file/d/1B69oDffW-q_2Xl1Z5z6K-K7v48b5zX9y/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_cine_wonder",
    uploaderName: "Citradhara Studios",
    uploaderHandle: "citradhara",
    uploaderAvatar: "/logo.jpg",
    category: "Cinema & Films",
    tags: ["cinematic", "travel", "culture", "wonders", "varanasi"],
    views: 48200,
    likesCount: 4210,
    dislikesCount: 18,
    commentsCount: 94,
    duration: "14:22",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "citra-2",
    title: "Raga Bhairav & Ambient Synthesizers: 24/7 Deep Flow & Concentration",
    description: "Ancient Indian melodic frameworks blended with modern ambient modular synthesizers. Designed for deep creative work, late night study, or meditation. Tune in to this stream of melodic wonders.",
    driveFileId: "1v7a8b9c0d1e2f3g4",
    driveUrl: "https://drive.google.com/file/d/1v7a8b9c0d1e2f3g4/view",
    embedUrl: "https://drive.google.com/file/d/1v7a8b9c0d1e2f3g4/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_soundscape",
    uploaderName: "Dhara Sounds",
    uploaderHandle: "dhara_music",
    uploaderAvatar: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=160&q=80",
    category: "Music & Audio",
    tags: ["music", "classical", "ambient", "meditation", "lofi"],
    views: 89300,
    likesCount: 8120,
    dislikesCount: 32,
    commentsCount: 180,
    duration: "45:00",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "citra-3",
    title: "Journey Across the Cosmic Horizon: James Webb & Deep Space Mysteries",
    description: "What lies beyond the oldest galaxies? An awe-inspiring exploration into stellar nurseries, gravitational lensing, and the cosmic stream of spacetime. Narrated with original scientific visualizations.",
    driveFileId: "1s9d8f7g6h5j4k3l2",
    driveUrl: "https://drive.google.com/file/d/1s9d8f7g6h5j4k3l2/view",
    embedUrl: "https://drive.google.com/file/d/1s9d8f7g6h5j4k3l2/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_cosmos",
    uploaderName: "Cosmos & Wonders",
    uploaderHandle: "cosmos_wonders",
    uploaderAvatar: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=160&q=80",
    category: "Science & Wonders",
    tags: ["space", "astronomy", "science", "physics", "universe"],
    views: 64100,
    likesCount: 6540,
    dislikesCount: 22,
    commentsCount: 142,
    duration: "28:15",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "citra-4",
    title: "Building Full-Stack Next.js & AI Web Applications | CodersHigh Stream",
    description: "Join the CodersHigh community as we engineer modern reactive web systems with Next.js App Router, Tailwind CSS, TypeScript, and AI models. Clean code, architecture, and live deployment.",
    driveFileId: "1k2j3h4g5f6d7s8a9",
    driveUrl: "https://drive.google.com/file/d/1k2j3h4g5f6d7s8a9/view",
    embedUrl: "https://drive.google.com/file/d/1k2j3h4g5f6d7s8a9/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_codershigh_admin",
    uploaderName: "CodersHigh",
    uploaderHandle: "codershigh",
    uploaderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
    category: "Coding & Tech",
    tags: ["coding", "nextjs", "webdev", "codershigh", "software"],
    views: 32400,
    likesCount: 2980,
    dislikesCount: 14,
    commentsCount: 76,
    duration: "42:10",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "citra-5",
    title: "The Art of Worldbuilding: Unreal Engine 5 & Next-Gen Cinematic Gaming",
    description: "Discover how artists and technical directors craft photorealistic virtual worlds using Nanite, Lumen, and procedural generation. A mesmerizing deep dive into the craft of digital worlds.",
    driveFileId: "1m9n8b7v6c5x4z3a2",
    driveUrl: "https://drive.google.com/file/d/1m9n8b7v6c5x4z3a2/view",
    embedUrl: "https://drive.google.com/file/d/1m9n8b7v6c5x4z3a2/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_game_craft",
    uploaderName: "Karan Johar",
    uploaderHandle: "pixel_craft",
    uploaderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
    category: "Gaming",
    tags: ["gaming", "unrealengine", "3d", "art", "gamedev"],
    views: 51200,
    likesCount: 4890,
    dislikesCount: 29,
    commentsCount: 110,
    duration: "21:40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "citra-6",
    title: "Philosophy, Curiosity & Creative Mastery | Conversations on the Mind",
    description: "An intimate dialogue exploring human creativity, memory palaces, deep focus, and how curiosity shapes civilization. Thoughtful reflections for curious creators.",
    driveFileId: "1q2w3e4r5t6y7u8i9",
    driveUrl: "https://drive.google.com/file/d/1q2w3e4r5t6y7u8i9/view",
    embedUrl: "https://drive.google.com/file/d/1q2w3e4r5t6y7u8i9/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_talks",
    uploaderName: "The Open Mind",
    uploaderHandle: "open_mind",
    uploaderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
    category: "Podcasts & Talks",
    tags: ["podcast", "philosophy", "creativity", "mindset", "conversations"],
    views: 29400,
    likesCount: 2430,
    dislikesCount: 11,
    commentsCount: 65,
    duration: "38:50",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
  },
  {
    id: "citra-7",
    title: "A Day in the Mountains: Cinematic Filmmaking, Quiet Routines & Solo Vlog",
    description: "Waking up above the clouds in the Himalayas. Join me for a day of capturing mountain timelapses, creative routines, and thoughts on visual storytelling.",
    driveFileId: "1z8x7c6v5b4n3m2l1",
    driveUrl: "https://drive.google.com/file/d/1z8x7c6v5b4n3m2l1/view",
    embedUrl: "https://drive.google.com/file/d/1z8x7c6v5b4n3m2l1/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_vlogger",
    uploaderName: "Kabir Trails",
    uploaderHandle: "kabir_vlogs",
    uploaderAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
    category: "Vlogs",
    tags: ["vlog", "travel", "mountains", "filmmaking", "routine"],
    views: 37800,
    likesCount: 3410,
    dislikesCount: 15,
    commentsCount: 88,
    duration: "18:25",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  }
];

export const INITIAL_COMMENTS: Record<string, Comment[]> = {
  "citra-1": [
    {
      id: "comm-1",
      videoId: "citra-1",
      userId: "user-commenter-1",
      userName: "Devansh Mehta",
      userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
      text: "The visuals and sound design of Varanasi are breathtaking. Citradhara is such a beautiful platform!",
      likes: 42,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
    {
      id: "comm-2",
      videoId: "citra-1",
      userId: "user-commenter-2",
      userName: "Ananya Rao",
      userAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=120&q=80",
      text: "Streaming right from Google Drive with zero ads and zero lag is amazing. Pure stream of wonders.",
      likes: 27,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    }
  ]
};
