import { Video, Comment } from "@/types";

export const INITIAL_VIDEOS: Video[] = [
  {
    id: "citra-1",
    title: "Building Full-Stack Next.js & AI Web Applications | CodersHigh Masterclass",
    description: "Welcome to Citradhara - A Stream of Wonders! In this extensive session by the CodersHigh community, we explore building end-to-end full stack web applications with Next.js App Router, Tailwind CSS, TypeScript, and AI integrations. Learn how to architect clean codebases, optimize performance, and deploy to Vercel for free.",
    driveFileId: "1p0GqLq1j9g6v5n0d", // Demo Drive file ID
    driveUrl: "https://drive.google.com/file/d/1B69oDffW-q_2Xl1Z5z6K-K7v48b5zX9y/view",
    embedUrl: "https://drive.google.com/file/d/1B69oDffW-q_2Xl1Z5z6K-K7v48b5zX9y/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_codershigh_admin",
    uploaderName: "CodersHigh HQ",
    uploaderHandle: "codershigh",
    uploaderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
    category: "Web Development",
    tags: ["nextjs", "react", "fullstack", "codershigh", "citradhara"],
    views: 14820,
    likesCount: 1240,
    dislikesCount: 14,
    commentsCount: 38,
    duration: "42:15",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "citra-2",
    title: "The Wonder of Neural Networks: Deep Learning from First Principles",
    description: "Dive deep into the mathematical wonders of backpropagation, tensor operations, and attention mechanisms. A cinematic coding visualizer explaining how modern LLMs understand language, crafted exclusively for Citradhara.",
    driveFileId: "1v7a8b9c0d1e2f3g4",
    driveUrl: "https://drive.google.com/file/d/1v7a8b9c0d1e2f3g4/view",
    embedUrl: "https://drive.google.com/file/d/1v7a8b9c0d1e2f3g4/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_ai_wonder",
    uploaderName: "Aarav Sharma",
    uploaderHandle: "aarav_ai",
    uploaderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
    category: "Artificial Intelligence",
    tags: ["ai", "machine-learning", "deep-learning", "python"],
    views: 28950,
    likesCount: 2310,
    dislikesCount: 21,
    commentsCount: 84,
    duration: "35:40",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "citra-3",
    title: "Distributed Systems & High-Scale Architecture: Handling 10M Requests",
    description: "How does a modern video streaming service scale to millions of concurrent streams? We dissect load balancers, caching tiers (Redis), database sharding, and edge CDNs in this comprehensive architecture session.",
    driveFileId: "1s9d8f7g6h5j4k3l2",
    driveUrl: "https://drive.google.com/file/d/1s9d8f7g6h5j4k3l2/view",
    embedUrl: "https://drive.google.com/file/d/1s9d8f7g6h5j4k3l2/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_system_expert",
    uploaderName: "Priya Varma",
    uploaderHandle: "priya_systems",
    uploaderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
    category: "System Design",
    tags: ["systemdesign", "architecture", "scalability", "redis"],
    views: 45200,
    likesCount: 3890,
    dislikesCount: 30,
    commentsCount: 112,
    duration: "58:10",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "citra-4",
    title: "Mastering Graph Algorithms & Dynamic Programming for FAANG Interviews",
    description: "Unravel the elegance of Graph Traversals (BFS, DFS, Dijkstra) and 2D Dynamic Programming patterns. Visualizing state transitions step-by-step with clean Python & C++ solutions.",
    driveFileId: "1k2j3h4g5f6d7s8a9",
    driveUrl: "https://drive.google.com/file/d/1k2j3h4g5f6d7s8a9/view",
    embedUrl: "https://drive.google.com/file/d/1k2j3h4g5f6d7s8a9/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1516116211227-bbc14188f58b?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_dsa_guru",
    uploaderName: "Rohan Gupta",
    uploaderHandle: "rohan_algos",
    uploaderAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
    category: "Algorithms & DSA",
    tags: ["dsa", "algorithms", "leetcode", "graphs"],
    views: 19400,
    likesCount: 1650,
    dislikesCount: 12,
    commentsCount: 52,
    duration: "49:22",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "citra-5",
    title: "Modern Kubernetes & Docker Zero-to-Hero: Free Cloud Deployment",
    description: "Demystifying containers, pods, ingress controllers, and CI/CD pipelines. Learn how to set up resilient microservices architectures using completely free development tiers and GitOps.",
    driveFileId: "1m9n8b7v6c5x4z3a2",
    driveUrl: "https://drive.google.com/file/d/1m9n8b7v6c5x4z3a2/view",
    embedUrl: "https://drive.google.com/file/d/1m9n8b7v6c5x4z3a2/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_devops_ninja",
    uploaderName: "Vikram Patel",
    uploaderHandle: "vikram_cloud",
    uploaderAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80",
    category: "DevOps & Cloud",
    tags: ["docker", "kubernetes", "devops", "cloud"],
    views: 11200,
    likesCount: 980,
    dislikesCount: 8,
    commentsCount: 29,
    duration: "31:05",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: "citra-6",
    title: "A Stream of Wonders: The History & Future of Indian Tech Innovation",
    description: "A cinematic documentary exploring India's software revolution: from early computing milestones to UPI, space missions, open-source revolutions, and the emerging wave of AI startups. A tribute to curiosity and creation.",
    driveFileId: "1q2w3e4r5t6y7u8i9",
    driveUrl: "https://drive.google.com/file/d/1q2w3e4r5t6y7u8i9/view",
    embedUrl: "https://drive.google.com/file/d/1q2w3e4r5t6y7u8i9/preview",
    thumbnailUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1280&q=80",
    uploaderUid: "user_citradhara_stories",
    uploaderName: "Citradhara Studios",
    uploaderHandle: "citradhara",
    uploaderAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=160&q=80",
    category: "Cinematic Tech Stories",
    tags: ["stories", "documentary", "citradhara", "tech-history"],
    views: 64100,
    likesCount: 7820,
    dislikesCount: 45,
    commentsCount: 240,
    duration: "24:18",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  }
];

export const INITIAL_COMMENTS: Record<string, Comment[]> = {
  "citra-1": [
    {
      id: "comm-1",
      videoId: "citra-1",
      userId: "user-commenter-1",
      userName: "Devansh Mehta",
      userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
      text: "This Next.js masterclass is incredible! The explanation on App Router server actions and streaming is crystal clear. Citradhara is such an awesome platform for CodersHigh.",
      likes: 34,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
    {
      id: "comm-2",
      videoId: "citra-1",
      userId: "user-commenter-2",
      userName: "Ananya Rao",
      userAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=120&q=80",
      text: "Love how fast Google Drive videos load directly in this player. 100% free hosting is genius for our community!",
      likes: 19,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    }
  ]
};
